id: A45890F88
title: Aspiration of the Mahāmudrā of Definitive Meaning
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:47:54.089220
  last_modified_at: 2022-03-01 01:47:54.089228
